name: Replace strings in the generated website code
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Replace strings in the generated website code
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Replace strings
      run: |
      find . -type f -exec sed -i 's#blog-dynamic.codeberryschool.com#codeberryschool.com#g' {} +
      find . -type f -exec sed -i 's#<meta name="robots" content="nofollow, noindex">##g' {} +
      find . -type f -exec sed -i 's#"\\/wp-include#"\\/blog\\/wp-include#g' {} +
